POST http://localhost:8080/schedule
Content-Type: application/json

{
  "title": "Lecture",
  "dayOfWeek": "TUESDAY",
  "startTime": "08:00",
  "endTime": "20:00",
  "color": "#e03674"
}

###

GET http://localhost:8080/calendar/week?startDate=2026-03-16


